language: php
php:
  - 7.4

install:
  - travis_retry composer install --no-progress --prefer-dist # Install dependencies

jobs:
  include:
    - stage: Quality Assurance
      php: 7.4
      script:
        - make qa

    - stage: coverage
      php: 7.4
      script:
        - make coverage

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
