language: php
php:
  - 7.4

install:
  - travis_retry composer install --no-progress --prefer-dist # Install dependencies

jobs:
  include:
    - stage: Quality Assurance
      php: 7.4
      script:
        - make qa

    - stage: coverage
      php: 7.4
      script:
        - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        - php php-coveralls.phar --verbose

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
